name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: YanGuilhermeDev
          outputs: dist

      - name: Setup git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Switch to output branch or create if missing
        run: |
          if git show-ref --quiet refs/heads/output; then
            git checkout output
          else
            git checkout --orphan output
            git rm -rf .
            git commit --allow-empty -m "Initialize output branch"
            git push origin output
          fi

      - name: Copy files to repo root
        run: |
          cp -r dist/* .
          git add .
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push origin output --force
